### ISSUE TITLE
VersionedModelAdmin Class breaks compatibility with silverstripe-versioned-gridfield

### ISSUE THREAD

**Issue by adrexia** [heyday/silverstripe-versioneddataobjects#17]
We have a few projects that use this module in conjuction with Versioned gridfield (https://github.com/icecaster/silverstripe-versioned-gridfield). Unfortunately, as of this commit: https://github.com/heyday/silverstripe-versioneddataobjects/commit/9df0bee183bccd3d1579a109d28c8c9212371136 
we are getting namespace errors when we try to update as VersionedModelAdmin exists in both dependencies.

**Comment by stecman** [comment]
Votes? I'd say 1, but throwing an alternative in for the sake of it:

1. add a namespace and release as a new major version, or
2. add a `_manifest_exclude` file in the code directory and use Composer's autoloading rather than SilverStripe's class manifest (would prevent the module being used without composer).

In the meantime, if you had to make this work you could work it with a [`post-install-cmd`/`post-update-cmd`](https://getcomposer.org/doc/articles/scripts.md#command-events) in composer that removed the offending file.

**Comment by stevie-mayhew** [comment]
I'd vote for 1.

**Comment by adrexia** [comment]
1 sounds more robust.

**Comment by camspiers** [comment]
I vote 1 too.

**Comment by glenn-bautista** [comment]
I vote 1

**Comment by tamelion** [comment]
I like option 1.

**Comment by Leapfrognz** [comment]
Option 1

**Comment by assertchris** [comment]
Option 1

**Comment by stecman** [comment]
Released namspaces in `2.0.0`. Thanks @assertchris!
